### ISSUE TITLE
Blank sidebar

### ISSUE THREAD

**Issue by mddarmawan** [ainuls/funtasting#2]
This issue comes when you opened this at desktop with mobile view.

There is blank sidebar when you closed the sidebar and then you resize your view to default.

[View](http://imgur.com/cA40sTV)

**Comment by ilhamdoanggg** [comment]
yups, not responsive for any device
http://imgur.com/0x9KFxX

**Comment by ainuls** [comment]
Hei thanks guys for your inputs. I will fix this isue immidiately.
